FROM node:18

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install -g @nestjs/cli
RUN SHARP_IGNORE_GLOBAL_LIBVIPS=1 npm install --arch=x64 --platform=linux sharp
RUN npm install

VOLUME [ "/app" ]

CMD npm run start:dev
